version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advisors-api
    environment:
      DATABASE_URL: postgresql+psycopg2://advisor:advisor@postgres:5432/advisor_code_analyzer
      REDIS_URL: redis://redis:6379/0
      LOG_LEVEL: INFO
      MODEL_PROVIDER: openai
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 10
  postgres:
    image: postgres:16-alpine
    container_name: advisors-postgres
    environment:
      POSTGRES_USER: advisor
      POSTGRES_PASSWORD: advisor
      POSTGRES_DB: advisor_code_analyzer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U advisor -d advisor_code_analyzer"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    container_name: advisors-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:


